### ISSUE TITLE
Symbol "GET-PROGRAM-RESOURCE-INDEX" not found in the CL-OPENGL package.

### ISSUE THREAD

**Issue by cbaggers** [mfiano/shadow#3]
Found by running `(asdf:load-system :shadow :force t :verbose t)`

that symbol is exported from `%gl` though so that might be the answer

Making that change did allow shadow to load arbeit with the following

```
; compilation unit finished
;   Undefined variables:
;     SHADOW::*ACTIVE-SHADER-PROGRAM* SHADOW::*SHADER-INFO*
;   caught 5 WARNING conditions
;   caught 3 STYLE-WARNING conditions
```
The style warnings were just from `declaim`ing things inline after they we used

**Comment by mfiano** [comment]
I'll look into this in the next day or 2 when I get some free time. Thanks!

**Comment by mfiano** [comment]
@cbaggers I fixed the warnings you mentioned in your issue text, however I cannot reproduce the warning you have with `get-program-resource-index` as in the issue title. Additionally:

```lisp
CL-USER> (describe 'gl:get-program-resource-index)
CL-OPENGL:GET-PROGRAM-RESOURCE-INDEX
  [symbol]

GET-PROGRAM-RESOURCE-INDEX names a compiled function:
  Lambda-list: (CL-OPENGL::PROGRAM CL-OPENGL::INTERFACE CL-OPENGL::NAME)
  Derived type: (FUNCTION (T T T) (VALUES T &OPTIONAL))
  Source file: /home/mfiano/.roswell/lisp/quicklisp/dists/quicklisp/software/cl-opengl-20180228-git/gl/state.lisp
; No values
```

Please verify you are on a recentish cl-opengl.

**Comment by mfiano** [comment]
@cbaggers Ah yeah. You must have an old copy of cl-opengl in your asdf registry. This GL function was wrapped about 2 months ago in cl-opengl 9e98625e4253f9231f19efd1ff21f6f258d2284a

**Comment by cbaggers** [comment]
thanks mate
